### ISSUE TITLE
make: *** [sg2vgproto.o] Error 1

### ISSUE THREAD

**Issue by fbemm** [ComparativeGenomicsToolkit/hal2vg#2]
I am trying to compile with g++ (GCC) 5.4.0 and get the following error:

sg2vgproto.cpp:85:79: error: ‘ceil’ was not declared in this scope    int seqChunks = (int)ceil((double)_sg->getNumSequences() / sequencesPerChunk);

**Comment by glennhickey** [comment]
I can't reproduce with my compiler.  Does adding

#include <cmath> to the top of sg2vgproto.cpp fix it?

thanks

**Comment by rojinsafavi** [comment]
I had the same issue and I solved the error by adding #include <cmath> to sg2vgproto.cpp. 
But, I'm getting a new error when I execute "make":

ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [hal2vg] Error 1

I'm using macOS Sierra version 10.12.1.
